name: Integration Workflow

on:
  schedule:
    - cron: "0 0 0/12 1/1 * ? *"

  workflow_dispatch:

jobs:
  tests:
    name: Run Integration Tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Pip
        run: pip install --user --upgrade pip
      - name: Install Dependencies
        run: pip install -e .[test]
      - name: Run integration tests
        run: pytest -v -m "integration"
